config/routes.rb
Rails.application.routes.draw do
  get 'welcome/Home'

  get 'welcome/Contact'

  get 'welcome/About'

  devise_for :users
  resources :posts
  root to: 'welcome#Home'
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :image

  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :image, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def Home
  end

  def Contact
  end

  def About
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photouploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/nav' %>

<%= yield %>

<footer>
	<p><center>Copyright &copy; - 2016 PhotoUploader</center></p>
</footer>
</body>
</html>

app/views/partials/_nav.html.erb
<style>
	#nav {
		padding: 0 50px 0 40px;
	}
</style>

<nav class="navbar navbar-fixed-top">
	<container class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#nav">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>

		<div class="collapse navbar-collapse" id="nav">
			<ul class="nav navbar-nav">
				<%= link_to 'Home |', welcome_Home_path%>
				<%= link_to ' Contact Us |', welcome_Contact_path%>
				<%= link_to ' About Us', welcome_About_path%>
			</ul>
			<ul class="nav navbar-nav navbar-right">
			 <% if current_user %>
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">Dropdown <span class="caret"></span></a>
	        	<ul class="dropdown-menu">
			 		<%= link_to 'Upload Photo', new_post_path %><br>
			 		<%= link_to 'My Account', posts_path %>
			 	</ul>
			 		<%= link_to ' Sign Out', destroy_user_session_path, method: :delete %>
			 <% else %>
					<%= link_to 'Sign In |', new_user_session_path %>
					<%= link_to ' Register', new_user_registration_path %>
			 <% end %>
			</ul>
		</div>
	</container>
</nav>

app/views/posts/_form.html.erb
    <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit class: 'btn btn-success btn-block', style: 'padding-top: 10px;' %>
    </div>
  <% end %>

app/views/posts/edit.html.erb
<!-- container -->
<div class="container">
	 <h1>Editing Post</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', posts_path %>
</div><!-- /container -->

app/views/posts/index.html.erb
<!-- container -->
<div class="container">
   <p id="notice"><%= notice %></p>

  <h1>Listing Posts</h1>

      <% @posts.each do |post| %>
        
         <h4 class="postdis">Title</h4><%= post.title %><br>
          <a href="<%= post_url(post) %>"><%= image_tag(post.image.profile_size.url) %></a><br>
          <h4 class="postdis">Description</h4><%= post.description %><br>
          <%= link_to 'Show |', post %>
          <%= link_to ' Edit |', edit_post_path(post) %>
          <%= link_to ' Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %><br><br>
        
      <% end %>
  

  <br>

  <%= link_to 'New Post', new_post_path %>
  </div><!-- /container -->

app/views/posts/new.html.erb
<!-- container -->
<div class="container">
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h1>New Post</h1>
			</div>
			<div class="panel-body">
				<%= render 'form' %>
			</div>
			<%= link_to 'Back', posts_path %>
		</div>
	</div>
</div>
	 
</div><!-- /container -->

app/views/posts/show.html.erb
<!-- container -->
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Title:</strong>
	  <%= @post.title %>
	</p>

	<p>
	  <strong>Image:</strong>
	  <%= image_tag(@post.image.profile_size.url) %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @post.description %>
	</p>

	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Back', posts_path %> 
	</div><!-- /container -->

app/views/welcome/About.html.erb
<!-- container -->
<div class="container">
	<h1>Welcome#About</h1>
	<p>Find me in app/views/welcome/About.html.erb</p>	 
</div><!-- /container -->

app/views/welcome/Contact.html.erb
<!-- container -->
<div class="container">
	<h1>Welcome#Contact</h1>
	<p>Find me in app/views/welcome/Contact.html.erb</p>	 
</div><!-- /container -->

app/views/welcome/Home.html.erb
<head>
  <style>
    body, html {
      height: 100%;
      margin: 0;
      font: 400 15px/1.8 "Lato", sans-serif;
      color: #777;
    }
    
    .bgimg-1, .bgimg-2, .bgimg-3 {
      position: relative;
      background-attachment: fixed;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
    
    }
    .bgimg-1 {
      background-image: url("https://images.unsplash.com/uploads/141219200475673afcb68/f5bd8360?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=4730930ba1fb54eef0d7dc616bb54f36");
      min-height: 100%;
    }
    
    .bgimg-2 {
      background-image: url("https://hd.unsplash.com/photo-1444658293155-105ae40f8278");
      min-height: 400px;
    }
    
    .bgimg-3 {
      background-image: url("https://hd.unsplash.com/photo-1452390211826-8d50e8ee0b62");
      min-height: 400px;
    }
    
    .caption {
      position: absolute;
      left: 0;
      top: 50%;
      width: 100%;
      text-align: center;
      color: #000;
    }
    
    .caption span.border {
      background-color: #111;
      color: #fff;
      padding: 0px;
      font-size: 25px;
      letter-spacing: 10px;
    }
    
    h3 {
      letter-spacing: 5px;
      text-transform: uppercase;
      font: 20px "Lato", sans-serif;
      color: #111;
    }
  </style>
</head>

<body>
  <div class="bgimg-1">
    <div class="caption">
      <span class="border" style="background-color:transparent;font-size:25px;color: black;"><center>PhotoUploader<br>(SCROLL DOWN)</center></span>
    </div>
  </div>

  <div style="color: #777;background-color:white;text-align:center;padding:50px 80px;text-align: justify;">
    <h3 style="text-align:center;">PhotoUploader Info</h3>
    <p><center>PhotoUploader is a simple photo uploading website.  You can join for free and upload your favorite photos to be saved securely. Just register for free and all your information will be kept completely private.</center></p>
  </div>

  <div class="bgimg-2">
  </div>

  <div style="position:relative;">
    <div style="color:#ddd;background-color:#282E34;text-align:center;padding:50px 80px;text-align: justify;">
      <p>Join now it's free for.  &nbsp; No financial info is required.  Click <%= link_to 'Here', new_user_registration_path %></a></p>
    </div>
  </div>

  <div class="bgimg-3">
  </div>

  <div style="position:relative;">
    <div style="color:#ddd;background-color:#282E34;text-align:center;padding:50px 80px;text-align: justify;">
      <p>If you have photos to lose, then please join, and you will not lose them.  Click <%= link_to 'Here', new_user_registration_path %></p>
    </div>
  </div>

  <div class="bgimg-1">
    <div class="caption">
      <span class="border" style="background-color:transparent;font-size:25px;color: black;">ALRIGHT! LET'S DO THIS!</span>
    </div>
  </div>

</body>

</html>